const config = {
  API_URL: import.meta.env.VITE_API_URL,
  DEFAULT_DISPLAY_TIMEOUT: 5000,
  DEFAULT_EXPONENTIAL_BACKOFF_RETRIES: 3,
  DEFAULT_EXPONENTIAL_BACKOFF_INITIAL_DELAY: 1000,
  DEFAULT_SCROLL_TRIGGER_PERCENTAGE: 33,
  SESSION_STORAGE_KEY: 'campaign-engagement-vector-dismissed',
} as const;

export default config;
